idf_component_register(SRCS "main.c"
                       INCLUDE_DIRS "."
                       REQUIRES 
                        esp32-camera 
                        driver 
                        esp_driver_uart
                        esp_wifi
                        bt
                       )
